---
engines:
  checkstyle:
    enabled: true
    channel: "beta"
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - java
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.java"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- src/main/webapp/WEB-INF/js/materialize/
- src/main/webapp/WEB-INF/js/src-noconflict/
- src/main/webapp/WEB-INF/css/materialize/
- src/main/java/in/ac/bits/protocolanalyzer/
