language: java
jdk: oraclejdk8

install: true

before_script:
  - npm install -g csslint

script:
  - mvn test -B
  - csslint src/main/webapp/WEB-INF/css/main.css

after_success:
  - mvn clean test jacoco:report coveralls:report || echo "========Tests failed========"
  - mvn pmd:pmd || echo "========PMD checks failed========"
  - mvn checkstyle:checkstyle || echo "========CheckStyle checks failed========"
  - mvn findbugs:findbugs || echo "========FindBugs checks failed========"
  - mvn site
